// src/lib/utils/emailService.ts

import nodemailer from 'nodemailer';

export const transporter = nodemailer.createTransport({
  host: 'smtp.office365.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD,
  },
  tls: {
    ciphers: 'SSLv3',
    rejectUnauthorized: true,
  },
});

export const sendApplicationEmail = async (
  companyName: string,
  to: string, // hiring contact or admin
  transcript: string,
  applicantName?: string,
  applicantEmail?: string,
  applicantPhone?: string
): Promise<boolean> => {
  try {
    const mailOptions = {
      from: '"OndeWork" <hello@ondework.com>',
      to,
      subject: `New Job Application - ${companyName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 5px;">
          <h2 style="color: #8c52ff;">New Application for ${companyName}</h2>
          <p><strong>Applicant Name:</strong> ${applicantName || 'Not provided'}</p>
          <p><strong>Email:</strong> ${applicantEmail || 'Not provided'}</p>
          <p><strong>Phone:</strong> ${applicantPhone || 'Not provided'}</p>
          
          <h3>Transcript:</h3>
          <pre style="background: #f9f9f9; padding: 10px; white-space: pre-wrap; border: 1px solid #ccc; border-radius: 4px;">
${transcript}
          </pre>

          <p style="font-size: 12px; color: #888; margin-top: 20px;">
            This message was generated by the OndeWork Apply Now Chat Agent on ${new Date().toLocaleString()}.
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`📨 Application email sent to ${to}, messageId: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error('❌ Error sending application email:', error);
    throw error;
  }
};